let bruxos = [
    {
        id: 1,
        nome: "Harry Potter",
        casa: "Grifinória",
        ano: 7,
        varinha: "Azevinho e pena de fênix, 28cm",
        mascote: "Coruja (Edwiges)",
        patrono: "Cervo",
        especialidade: "Sobreviver a Voldemort 😎",
    },
    {
        id: 2,
        nome: "Hermione Granger",
        casa: "Grifinória",
        ano: 7,
        varinha: "Videira e fibra de coração de dragão, 27cm",
        mascote: "Gato (Bichento)",
        patrono: "Lontra",
        especialidade: "Saber tudo de tudo",
    },
    {
        id: 3,
        nome: "Ron Weasley",
        casa: "Grifinória",
        ano: 7,
        varinha: "Salgueiro e crina de unicórnio, 35cm",
        mascote: "Rato (Perebas)",
        patrono: "Terrier Jack Russell",
        especialidade: "Xadrez Bruxo",
    },
    {
        id: 4,
        nome: "Draco Malfoy",
        casa: "Sonserina",
        ano: 7,
        varinha: "Espinheiro e crina de unicórnio, 25cm",
        mascote: "Coruja (não nomeada)",
        patrono: "Desconhecido",
        especialidade: "Ser irritante",
    },
    {
        id: 5,
        nome: "Luna Lovegood",
        casa: "Corvinal",
        ano: 6,
        varinha: "Madeira de cerejeira e núcleo desconhecido",
        mascote: "Nenhum",
        patrono: "Lebre",
        especialidade: "Ver criaturas imaginárias (ou não) 👻",
    },
    {
        id: 6,
        nome: "Neville Longbottom",
        casa: "Grifinória",
        ano: 7,
        varinha: "Cerejeira e pelo de unicórnio, 30cm",
        mascote: "Sapo",
        patrono: "Não conhecido",
        especialidade: "Herbologia avançada",
    },
    {
        id: 7,
        nome: "Cho Chang",
        casa: "Corvinal",
        ano: 7,
        varinha: "Salgueiro e fibra de coração de dragão, 23cm",
        mascote: "Coruja(não nomeada)",
        patrono: "Cisne",
        especialidade: "Quadribol (Apanhadora)",
    },
    {
        id: 8,
        nome: "Cedrico Diggory",
        casa: "Lufa-Lufa",
        ano: 7,
        varinha: "Freixo e pelo de unicórnio, 32cm",
        mascote: "nenhum",
        patrono: "Não conhecido",
        especialidade: "Cavalheirismo",
    },
        {
        id: 9,
        nome: "Bellatrix Lestrange",
        casa: "Sonseria",
        ano: 6,
        varinha: "Nogueira e fibra de coração de dragão, 32cm",
        mascote: "Nenhum",
        patrono: "Não conhecido",
        especialidade: "Arte das trevas",
    },
    {
        id: 10,
        nome: "Minerva McGonagali",
        casa: "Grifinória",
        ano: 9,
        varinha: "Aberto e fibra de coração de dragão, 24cm",
        mascote: "Gato",
        patrono: "Gato",
        especialidade: "Transfiguração",
    },
    {
        id: 11,
        nome: "Severo Snape",
        casa: "Sonserina",
        ano: 9,
        varinha: "Ébano e fibra de coração de dragão, 33cm",
        mascote: "Nenhum",
        patrono: "Corça",
        especialidade: "Poções (e segredos)",
    },
    {
        id: 12,
        nome: "Sirius Black",
        casa: "Grifinória",
        ano: 7,
        varinha: "Nogal e fibra de coração de dragão, 28cm",
        mascote: "Nenhum",
        patrono: "Cão",
        especialidade: "Animago não registrado 🐶",
    },
    {
        id: 13,
        nome: "Remo Lupin",
        casa: "Grifinória",
        ano: 7,
        varinha: "Cipreste e crina de unicórnio, 26cm",
        mascote: "Nenhum",
        patrono: "Lobo",
        especialidade: "Defesa Contra as Artes das Trevas",
    },
    {
        id: 14,
        nome: "Ninfadora Tonks",
        casa: "Lufa-Lufa",
        ano: 7,
        varinha: "Avelã e pelo de unicórnio, 29cm",
        mascote: "Nenhum",
        patrono: "Coelho (mudou para Lobo após conhecer Lupin)",
        especialidade: "Metamorfomagia 💇‍♀️",
    },
    {
        id: 15,
        nome: "Alvo Dumbledore",
        casa: "Grifinória",
        ano: 9,
        varinha: "Sabugueiro e pelo de testrálio, 38cm (Varinha das Varinhas)",
        mascote: "Fênix (Fawkes)",
        patrono: "Fênix",
        especialidade: "Ser um gênio misterioso 🧙‍♂️",
    }
  ];
  
  export default bruxos;